#!/usr/bin/env python3
"""
check_updates.py — propose updates to the website.

Run periodically (called by _update/run_updates.sh by default). Reads:
- Current website source (research.qmd, cv.qmd, index.qmd, plus master CV)
- _notes/workplan.md (current project status dashboard)
- Recent git log across the Projects/ monorepo (last 60 days)
- Each project's CLAUDE.md heading section, where present

Asks Claude what should change on the website. Writes a proposed-edits report
to website/_proposed_updates_<date>.md (gitignored). The report is for Noah to
read and selectively apply — this script never edits source files.

Cost: ~30K input tokens, ~5K output tokens. Sonnet 4.6 = roughly $0.15/run.
"""

import os
import sys
import subprocess
from datetime import datetime, timedelta
from pathlib import Path

import dotenv
import anthropic

PROJECTS = Path(os.path.expanduser("~/Dropbox/Projects"))
WEBSITE = PROJECTS / "me" / "website"
CV_DIR = PROJECTS / "me" / "cv"
NOTES = PROJECTS / "_notes"

MODEL = "claude-sonnet-4-6"
MAX_OUT = 8000

# Source files the LLM will read & potentially propose edits to
WEBSITE_FILES = [
    WEBSITE / "index.qmd",
    WEBSITE / "research.qmd",
    WEBSITE / "cv.qmd",
    CV_DIR / "cv.qmd",
]

CONTEXT_FILES = [
    NOTES / "workplan.md",
    PROJECTS / "CLAUDE.md",
]

GIT_LOOKBACK_DAYS = 60


def load_env():
    # Anthropic key lives in eventsData/.env per project convention.
    dotenv.load_dotenv(PROJECTS / "eventsData" / ".env", override=True)
    if not os.environ.get("ANTHROPIC_API_KEY"):
        sys.exit("ERROR: ANTHROPIC_API_KEY not in eventsData/.env")


def read_text(path: Path, max_chars: int = 50_000) -> str:
    if not path.exists():
        return f"<{path}: file not found>"
    s = path.read_text(errors="replace")
    if len(s) > max_chars:
        s = s[:max_chars] + f"\n\n... [truncated at {max_chars} chars]"
    return s


def recent_git_activity() -> str:
    """One-line-per-commit log of the last GIT_LOOKBACK_DAYS days."""
    since = (datetime.now() - timedelta(days=GIT_LOOKBACK_DAYS)).strftime("%Y-%m-%d")
    try:
        out = subprocess.check_output(
            ["git", "-C", str(PROJECTS), "log",
             f"--since={since}", "--oneline", "--no-merges"],
            text=True, stderr=subprocess.STDOUT, timeout=30,
        )
        return out.strip() or "(no commits in window)"
    except Exception as exc:
        return f"<git log failed: {exc}>"


def assemble_prompt() -> str:
    parts = ["# Website source files\n"]
    for p in WEBSITE_FILES:
        parts.append(f"## `{p.relative_to(PROJECTS)}`\n\n```\n{read_text(p)}\n```\n")

    parts.append("\n# Project context\n")
    for p in CONTEXT_FILES:
        parts.append(f"## `{p.relative_to(PROJECTS)}`\n\n```\n{read_text(p, 30_000)}\n```\n")

    parts.append(f"\n# Recent git activity (last {GIT_LOOKBACK_DAYS} days)\n\n```\n")
    parts.append(recent_git_activity())
    parts.append("\n```\n")
    return "\n".join(parts)


SYSTEM = """You are reviewing Noah Buckley's academic website for staleness.

Your task: identify specific edits that should be made based on changes in
the project workplan, recent commits, or other context provided. Be
conservative — propose edits only when there is concrete evidence (a paper
moved status, a new working paper appeared, a conference presentation
happened, an academic appointment changed, etc.).

DO NOT propose:
- Stylistic rewrites
- New sections to add unless content for them clearly exists
- Speculative additions ("you might want to mention...")
- Things that look fine as-is

Output format: a markdown report with one section per file that needs
edits. Inside each section, show the proposed edit as a unified-diff-style
"before / after" pair. End with a brief summary of confidence.

If nothing meaningful changed and no updates are warranted, say so plainly
in one paragraph and stop. That is a valid and welcome answer.

Today's date: """ + datetime.now().strftime("%Y-%m-%d") + "."


def main() -> int:
    load_env()
    client = anthropic.Anthropic()
    user_msg = assemble_prompt()

    print(f"[check_updates] context size: {len(user_msg):,} chars", file=sys.stderr)
    resp = client.messages.create(
        model=MODEL,
        max_tokens=MAX_OUT,
        system=SYSTEM,
        messages=[{"role": "user", "content": user_msg}],
    )

    body = resp.content[0].text
    out_path = WEBSITE / f"_proposed_updates_{datetime.now():%Y-%m-%d}.md"
    header = (
        f"# Proposed website updates — {datetime.now():%Y-%m-%d %H:%M}\n\n"
        f"Generated by `check_updates.py`. Source files reviewed: "
        f"{', '.join(p.name for p in WEBSITE_FILES)}.\n"
        f"Tokens used: input {resp.usage.input_tokens:,}, "
        f"output {resp.usage.output_tokens:,}.\n\n---\n\n"
    )
    out_path.write_text(header + body)
    print(f"[check_updates] wrote {out_path}", file=sys.stderr)
    print(out_path)  # stdout: caller can capture path
    return 0


if __name__ == "__main__":
    sys.exit(main())
