---
title: "CV"
---

[Download PDF](files/nbuckley_CV.pdf){.cv-pdf-link}

## Research Interests

Comparative politics; authoritarian politics; Russian and post-communist politics; public opinion; corruption; political methodology and experimental methods; political economy; bureaucracy; policing.

## Academic Experience

**Assistant Professor (with tenure since 2023)**, Department of Political Science
Trinity College Dublin, University of Dublin, Ireland
*2019--present*

**Visiting Researcher**, NYU Jordan Center
New York University, New York
*September--December 2022*

**Postdoctoral Associate** (three-year research position, third year declined)
NYU Abu Dhabi, United Arab Emirates
*2017--2019*
Faculty mentors: Rebecca Morton (NYU) and Joshua Tucker (NYU)

**Research Fellow** | **Postdoctoral Researcher**
International Center for the Study of Institutions and Development
Higher School of Economics, Moscow, Russia
*2011--2022* | *January--August 2017*

## Education

**Columbia University in the City of New York**
Ph.D. in Political Science, 2017

**University of Wisconsin-Madison**
B.A. received 2006, Comprehensive Honors, Honors in Political Science; Phi Beta Kappa
Majors: Political Science, Russian Language and Culture

## Peer-Reviewed Publications

"The Demand for Elections under Autocracy: Regime Approval and the Elimination of Local Elections in Russia" (with Quintin Beazer and Ora John Reuter). *American Journal of Political Science*. Conditionally accepted, 2024.

"Endogenous Popularity: How Perceptions of Regime Support Affect the Popularity of Authoritarian Regimes" (with Kyle Marquardt, Ora John Reuter, and Ekaterina Tertytchnaya). *American Political Science Review*. 2024;118(2):1046-1052.

"Staying Out of Trouble: Criminal Cases Against Russian Mayors" (with Ora John Reuter, Michael Rochlitz, and Anton Aisin). *Comparative Political Studies* 55(9), 1539-1568. 2022.

"Who Reports Crime? Citizen Engagement with the Police in Russia and Georgia" (with Timothy Frye, Scott Gehlbach, and Lauren McCarthy). *Europe-Asia Studies* 73(1):8-35. 2021.

"Performance Incentives under Autocracy: Evidence from Russia's Regions" (with Ora John Reuter). *Comparative Politics* 51(2):239-266. 2019.

"Staring at the West through Kremlin-tinted glasses: Russian mass and elite divergence in attitudes toward the United States, European Union, and Ukraine before and after Crimea" (with Joshua A. Tucker). *Post-Soviet Affairs* 35(5-6):365-375. 2019.

"Local Elections in Authoritarian Regimes: An Elite-Based Theory with Evidence from Russian Mayoral Elections" (with Ora John Reuter, Guzel Garifullina, and Alexandra Shubenkova). *Comparative Political Studies* 49:5. 2016.

"Cooperating with the State: Evidence from Survey Experiments on Policing" (with Timothy Frye, Scott Gehlbach, and Lauren McCarthy). *Journal of Experimental Political Science* 3(2):124-139. 2016.

"The Political Economy of Russian Gubernatorial Elections and Appointments" (with Timothy Frye, Guzel Garifullina, and Ora John Reuter). *Europe-Asia Studies* 66:8. 2014.

"Elections, Appointments, and Human Capital: The Case of Russian Mayors" (with Guzel Garifullina, Ora John Reuter, and Alexandra Shubenkova). *Demokratizatsiya* 22:1. 2014.

## Working Papers

"A Watched Pot Boiling: Street Protest and Public Opinion in Authoritarian Russia," presented at ASEEES 2021.

"Rotten Eggs or Bad Apples: Corruption Arrests and Public Opinion in Authoritarian Russia."

"Economic Blame Attribution in Times of Boom and Bust: The Case of Authoritarian Russia," presented at EPSA 2018.

## Grants & Fellowships

Arts and Social Sciences Benefaction Fund, Trinity College Dublin, 2020, 2025

Dissertation Development Grant, Department of Political Science, Columbia University, 2014

William T.R. Fox Fellowship in Political Science, Graduate School of Arts and Sciences, Columbia University, 2013--2014

Summer Grant for field research, Columbia Center for the Study of Development Strategies, April 2010 (with David Szakonyi)

PepsiCo Fellowship for Travel/Research in the Former Soviet Union, Harriman Institute, April 2010

## Additional Research Experience

**Contributing Author**
Russia Political Economy Project in the Eurasia Program
Foreign Policy Research Institute
*2017--2018*

**Consultant and Research Assistant**
Project: Assessing Transition and Rent-Seeking in Poland, Russia, and China
Supervisor: Joel Hellman, The World Bank
*2015*

**Research Assistant**
Project: "The Social Impact of the Millennium Village Project in Rwanda"
The Earth Institute, Columbia University; Columbia Center for the Study of Development Strategies
*2011*

**Research Assistant**
Project: "Incentives for Implementation of Regulatory Reform -- A Comparative Survey of Federal and Regional Government Officials in Russia"
Supervisors: Ekaterina Zhuravskaya, Mikhail Pryadilnikov
Center for Economic and Financial Research (CEFIR), Moscow, Russia; The World Bank
*2008*

## Teaching Experience

**Instructor**, Trinity College Dublin

- Comparative Politics B: The Comparative Politics of the Developing World (undergraduate lecture)
- Russian Politics under Putin (postgraduate/Masters seminar)
- Varieties of Authoritarianism (postgraduate/Masters seminar)
- Russian Politics after Communism (undergraduate seminar)
- Public Opinion (undergraduate seminar)

**Co-Instructor**, Higher School of Economics

- Comparative Political Economy (graduate-level seminar), 2011--2013, 2017--2018

## Other Publications

"How popular is Putin, really?" blog post on *The Monkey Cage*, with Kyle L. Marquardt, Ora John Reuter and Katerina Tertytchnaya. April 13, 2022.

"Putin's approval has stayed strong over the years -- war in Ukraine could change that," article on *The Conversation*, republished on several news sites. March 2, 2022.

"Here's what you can expect from Putin's next 6 years," blog post on *The Monkey Cage*, with David Szakonyi. March 22, 2018.

"The End of the Vertical? Corruption and Stagnation in Putin's Fourth Term," blog post on Eurasianet and FPRI Geopoliticus. March 9 and 13, 2018.

"Corruption and Power in Post-Communist Russia," policy memo for FPRI *Russia Political Economy Project*. April 2018.

## Professional Service

**Journal Reviewer**: APSR, AJPS, JOP, BJPS, Comparative Politics, Problems of Post-Communism, Governance, Democratization, Europe-Asia Studies, Electoral Studies, Political Behavior, Comparative Political Studies, World Politics, Journal of Quantitative Description: Digital Media, Political Research Quarterly, Post-Soviet Affairs, Russian Politics.

**Departmental Service**

- Associate Director and Director of the MSc Program in International Politics, Trinity College Dublin, 2021--2024

**Memberships**: APSA, ASEEES, EPSA, BASEES

## Selected Presentations

- Invited talk at Dublin City U Politics Seminar, February 2025
- Invited talk at Oxford Internet Institute workshop, January 2024
- Invited talk at U Limerick PPA seminar, October 2023
- Invited talk at U Zurich politics seminar, 2022
- Invited talk at U Bremen, December 2021
- Invited talk, "Issues in Russian and Post-Communist Political Economy and Politics" seminar, Oxford University, 2021
- APSA (2012--2018, 2021)
- ASEEES (2011--2018, 2020--2021)
- EPSA (2012--2014, 2016--2019)
- Invited workshop: "Political Rents and Political Elites in Russia and Beyond," Oxford University, 2017
- BASEES (2017--2018)

## Skills

**Language**: English (native); Russian (proficient)
